[graph]
all-features = true

[advisories]
yanked = "deny"
ignore = ["RUSTSEC-2024-0436"]

[licenses]
confidence-threshold = 0.8
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MPL-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "CDLA-Permissive-2.0",
  "Unicode-3.0",
  "Zlib"
]
private = { ignore = false }

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
skip = [
  { name = "rustix", version = "=0.38.44" },
  { name = "unicode-width", version = "=0.1.14" },
  { name = "getrandom", version = "=0.2.17" },
  { name = "hashbrown", version = "=0.15.5" },
  { name = "itertools", version = "=0.13.0" },
  { name = "wasm-encoder", version = "=0.243.0" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
