[package]
name = "registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
flate2 = "1.1"
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
tar = "0.4"
tracing.workspace = true
plugin-host = { path = "../plugin-host" }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "default-tls"] }

[dev-dependencies]
proptest = "1.6"
tempfile = "3.17"

[lints]
workspace = true
